spec:
    appName:
        enabled: true
    kubePrometheusStack:
        enabled: false
    prometheusBlackboxExporter:
        enabled: false
    destination:
        clustername: test
        server: https://kubernetes.default.svc
        name: test
        project: kube-apps-monitoring
