{{ if .Values.spec.kubecleanup.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecleanup
  namespace: argo-cd
  annotations:
    recipients.argocd-notifications.argoproj.io: "{{.Values.spec.slackChannel}}"
  {{ toYaml .Values.spec.additionalMetadata | nindent 2}}
spec:
  destination:
    namespace: kube-addons
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.preprodInfraProject }}
  {{- with .Values.spec.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  source:
    path: {{ .Values.spec.appsAddonComonPath }}kube-cleanup
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
{{- end }}