{{ if .Values.spec.vpa.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa-operator
  namespace: argo-cd
  annotations:
    recipients.argocd-notifications.argoproj.io: "{{.Values.spec.slackChannel}}"
  {{ toYaml .Values.spec.additionalMetadata | nindent 2}}
spec:
  destination:
    namespace:  {{ .Values.spec.destination.project }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  {{- with .Values.spec.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  source:
    path: {{ .Values.spec.appsAddonComonPath }}vpa-operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values:  |
        vpa:
          recommender:
            image:
              repository: {{ .Values.spec.kubeSystem.vpa.recommender.image.repository }}
              tag: {{ .Values.spec.kubeSystem.vpa.recommender.image.tag }}
        goldilocks:
          image:
            repository: {{ .Values.spec.kubeSystem.vpa.goldilocks.image.repository}}
            tag: {{ .Values.spec.kubeSystem.vpa.goldilocks.image.tag }}
      valueFiles:
        - values.yaml
{{- end }}