#Project information
site_name: Metis BBD Kubernetes
site_description: Resources for Metis

# Repository
repo_name: bbdsoftware/metis-cluster-bootstraps
repo_url: https://github.com/bbdsoftware/metis-cluster-bootstraps

# Copyright
copyright: Copyright &copy; 2021

# Configuration
theme:
  name: material
  language: en
  features:
    - tabs
    - instant
  palette:
    primary: red
    accent: reds
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: assest/metisiconsmall.png
    repo: material/ship-wheel
  favicon: assest/metisiconsmall.png
  logo: assest/metisiconsmall.png

markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search # necessary for search to work