apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: spring-ref-microservice
  namespace: default
spec:
  components:
    - name: spring-ref-microservice
      type: microservice
      properties:
        image: kanzifucius/spring-boot-k8s-example
        port: 8080
      traits:
        - type: prommetrics
          properties:
            path: "actuator/prometheus"
            promLabels:
              "release": "kube-prometheus-stack-in-cluster"
        - type: slos
          properties:
            errorQuery: sum(rate(http_server_requests_seconds_count{job="spring-ref-microservice",status=~"(5..|429)"}[{{.window}}]))
            totalQuery: sum(rate(http_server_requests_seconds_count{job="spring-ref-microservice"}[{{.window}}]))
            owner: "example-owner"
            team: "example-team"
            objective: 99.9
            promLabels:
              "release": "kube-prometheus-stack-in-cluster"
              "app": "kube-prometheus-stack"



