spec:
    aws:
        enabled: true # enabled if running in aws eks
    destination:
        clustername: test
        server: https://kubernetes.default.svc # agocd registered server address
        name: test
        project: vela-system # agocd project name
