apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.spec.destination.project }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .Values.spec.destination.project}}
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: {{ .Values.spec.destination.project}}
      server: "*"
    - namespace: kube-addons-crossplane
      server: "*"

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: LimitRange
    - group: ''
      kind: NetworkPolicy
