{{ if .Values.spec.provider.aws.enabled -}}
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: 'registry.upbound.io/crossplane/provider-aws:{{.Values.spec.provider.aws.version}}'
  controllerConfigRef:
    name: provider-aws-controller-config
{{- end }}