spec:
    awsNodeTerminationHandler:
        enabled: true
    albIngressController:
        enabled: true
    aws:
        enabled: true
    destination:
        clustername: test
        server: https://kubernetes.default.svc
        name: test
        project: kube-addons-aws
        syncPolicy:
