apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9123'
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - name: http-status
            containerPort: 9123
          args:
          - autonomous
          - --policy-file=/policy.yml
          - --prometheus-collector
          - --prometheus-port=9123
          env:
          # in order to allow PowerfulSeal to not accidentally self-destruct
          # give it the pod name
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          # and the host ip
          - name: HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          volumeMounts:
            - name: policyfile
              mountPath: /policy.yml
              subPath: policy.yml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: policyfile
          configMap:
            name: {{ .Values.name }}