apiVersion: v2
appVersion: "1.0"
name: metis-apps-monitoring
version: 0.0.1
maintainers:
  - name: metisbbd
    email: metisbbd@bbdsoftware.com
description: >
  This is the description
long_description: |
  # APP of APPS Bootstrap for kube-monitoring

  This char contains all argo applications that would be deployed into the kube-addons namespace to provide for various
  capabilities

  ## Structure

  ### **Tempaltes:**


  - **Argo Applications**

      This folder contains the argo applications that would be deployed as part of kube-addons bootstraps

  - **ArgoConfig**

      This contains the project definitons  for the argo project
      This  contains the argo defintions for the namespaces kube-addons

  - **RBAC**

      This contains the rbac configs for the kube-addons ns

  ## Development
  ### Linting
  To run the linting test a util script called test.sh has been provided to run the ct tests via a docer container

  ## Helm Charts included as applications
   - kube-prometheus   : https://github.com/prometheus-operator/kube-prometheus
   - blackbox_exporter   : https://github.com/prometheus/blackbox_exporter



  ```