spec:
    kubePrometheusStack:
        enabled: true
    prometheusBlackboxExporter:
        enabled: false
    aws:
        enabled: true
    destination:
        clustername: test
        server: https://kubernetes.default.svc # agocd registered server address
        name: test # agocd registered server name
        project: kube-apps-monitoring # agocd project name
