spec:
    fuentdcloudwatch:
        enabled: true
    loki:
        enabled: false
    promtail:
        enabled: true
    lokiDistributed:
        enabled: true
    loggingOperator:
        enabled: false
    destination:
        clustername: test
        server: https://kubernetes.default.svc
        name: test
        project: kube-apps-logging
