apiVersion: v2
appVersion: "1.0"
name: metis-apps-addons
version: 0.0.1
maintainers:
  - name: metisbbd
    email: metisbbd@bbdsoftware.com
description: >
  Helm chart for the description of
long_description: |
  # APP of APPS Bootstrap for kube-oam

  This char contains all argo applications that would be deployed into the kube-addons namespace to provide for various
  capabilities

  ## Structure

  ### **Tempaltes:**


  - **Argo Applications**

      This folder contains the argo applications that would be deployed as part of kube-addons bootstraps

  - **ArgoConfig**

      This contains the project definitons  for the argo project
      This  contains the argo defintions for the namespaces kube-addons

  - **RBAC**

      This contains the rbac configs for the kube-addons ns

  ## Development
  ### Linting
  To run the linting test a util script called test.sh has been provided to run the ct tests via a docer container

  ## Helm Charts included as applications
  - reloader : https://github.com/stakater/Reloader
  - Descheduler for Kubernetes : https://github.com/kubernetes-sigs/descheduler
  - goldilocks : https://goldilocks.docs.fairwinds.com/
  - kube-downscaler : https://codeberg.org/hjacobs/kube-downscaler
  - refecltor : https://github.com/emberstack/kubernetes-reflector
  - kube-cleanup : https://github.com/lwolf/kube-cleanup-operator
  - valut injector : https://www.vaultproject.io/docs/platform/k8s/injector
  - gatekeeper :https://kubernetes.io/blog/2019/08/06/opa-gatekeeper-policy-and-governance-for-kubernetes/

  ```
