{{ if .Values.spec.aws.enabled -}}
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
    credentials:
      source: InjectedIdentity
{{- end }}